// packages/coding-components/templates/arcade-editor/react/src/components/ArcadeEditor.jsx
import React, { useEffect, useCallback } from "react";

import { loadData } from "../functions/load-data";

import "./ArcadeEditor.css";

export default function ArcadeEditor() {
  // useCallback to prevent the function from being recreated when the component rebuilds
  const initializeTheEditor = useCallback(async () => {
    // Get the Arcade editor element
    const arcadeEditorElt = document.querySelector("arcgis-arcade-editor");

    // Log script change events
    arcadeEditorElt.addEventListener("scriptChange", async (e) => {
      console.log("script:", e.detail);
      // console.log("outputType on script:", await arcadeEditorElt.getOutputType());
    });

    // Log editor diagnostics
    arcadeEditorElt.addEventListener("diagnosticsChange", async (e) => {
      console.log("diagnostics:", e.detail);
    });

    // Start loading data
    const data = await loadData();

    // Tells Arcade Editor to use the 'popup' profile and provides the necessary data used as
    // definition for the profile variables. Feature Layer and Web Map instances are used by the
    // Editor UX to help users understand the structure of data used.
    // Note that for the $feature variable, we pass the feature layer instance as for definition
    // the editor needs the metadata of the feature not an actual feature.
    arcadeEditorElt.profile = {
      id: "popup",
      definitions: {
        $feature: data.featureLayer,
        $layer: data.featureLayer,
        $map: data.webMap,
        $datastore: data.featureLayer,
      },
    };

    // Tells Arcade Editor to the following test data. The data provided must match the expected data for the
    // profile used.
    // Note that for test data, the feature must an instance of a feature. This is not used for user experience
    // but for actually executing the the Arcade expression in the editor.
    arcadeEditorElt.testData = {
      profileVariableInstances: {
        $feature: data.featureSet.features[0],
        $layer: data.featureLayer,
        $map: data.webMap,
        $datastore: data.featureLayer.url,
      }
    };

    // Set a script on the editor
    arcadeEditorElt.script = "$feature";

    // Remove scrim
    if (document.querySelector("calcite-scrim")) {
      document.querySelector("calcite-scrim").remove();
    }
  }, []);

  // Register a function that will execute after the current render cycle
  useEffect(() => {
    initializeTheEditor().catch(console.error);
  }, [initializeTheEditor]);

  return (
    <div>
      <div className="editor-wrapper">
        <arcgis-arcade-editor />
      </div>
      <calcite-scrim loading></calcite-scrim>
    </div>
  );
}

// packages/coding-components/templates/vue/src/components/ArcadeEditor.vue
<script setup>
import { ref, onMounted, toRaw } from "vue";

import { loadData } from "../utils/load-data";

// Read more about ref() at https://vuejs.org/api/reactivity-core.html#ref
const editor = ref(null);
const profile = ref(null);
const testData = ref(null);
const scrim = ref(null);

// Registers a callback to be called after the component has been mounted
// See: https://vuejs.org/api/composition-api-lifecycle.html#onmounted
onMounted(async () => {
  if (editor.value) {
    // Get data for the arcade editor profile and test data
    const data = await loadData();

    profile.value = {
      id: "popup",
      definitions: {
        $feature: data.featureLayer,
        $layer: data.featureLayer,
        $map: data.webMap,
        $datastore: data.featureLayer,
      },
    };

    testData.value = {
      profileVariableInstances: {
        $feature: data.featureSet.features[0],
        $layer: data.featureLayer,
        $map: data.webMap,
        $datastore: data.featureLayer.url,
      },
      spatialReference: {
        wkid: 4326,
      },
    };

    // Wait for the editorInstance to be defined
    const editorInstance = await editor.value.getEditorInstance();

    // Make changes to the editor's options
    editorInstance.updateOptions({
      // Enable the minimap in the editor
      // minimap: { enabled: true },
    });

    // Remove the scrim from the UI
    scrim.value.remove();
  } else {
    // not mounted yet, or the element was unmounted (e.g. by v-if)
    // noop
  }
});
</script>

<!-- Using shorthand v-bind for script, profile, and testData  -->
<!-- Read more about v-bind at https://vuejs.org/api/built-in-directives.html#v-bind -->

<!-- Using shorthand v-on for scriptChange and diagnosticsChange events -->
<!-- Read more about v-on at https://vuejs.org/guide/essentials/event-handling.html -->

<!-- toRaw() is required for profile and testData objects -->
<!-- Read more about toRaw() https://vuejs.org/api/reactivity-advanced.html#toraw -->

<template>
  <div>
    <div class="editor-wrapper">
      <arcgis-arcade-editor
        ref="editor"
        :script="`$feature;`"
        :profile="toRaw(profile)"
        :testData="toRaw(testData)"
        @arcgisScriptChange="
          async (e) => {
            console.log('script:', e.detail);
            console.log('outputType on script:', await editor.getOutputType());
          }
        "
        @arcgisDiagnosticsChange="
          (e) => {
            console.log('diagnostics:', e.detail);
          }
        "
      />
    </div>
    <calcite-scrim ref="scrim" loading />
  </div>
</template>
