// packages/map-components/templates/vue/src/App.vue
<script setup>
  import "@arcgis/map-components/dist/components/arcgis-map";
  import "@arcgis/map-components/dist/components/arcgis-search";
  import "@arcgis/map-components/dist/components/arcgis-legend";
</script>

<template>
  <arcgis-map item-id="d5dda743788a4b0688fe48f43ae7beb9">
    <arcgis-search position="top-right" />
    <arcgis-legend position="bottom-left" />
  </arcgis-map>
</template>

// packages/map-components/templates/svelte/src/App.svelte
<script>
  import "@arcgis/map-components/dist/components/arcgis-map";
  import "@arcgis/map-components/dist/components/arcgis-search";

  import "@arcgis/core/assets/esri/themes/dark/main.css";
</script>

<main>
  <arcgis-map item-id="d5dda743788a4b0688fe48f43ae7beb9">
    <arcgis-search position="top-right" />
  </arcgis-map>
</main>

<style>
  main,
  arcgis-map {
    padding: 0;
    margin: 0;
    width: 100vw;
    height: 100vh;
  }
</style>
